### ISSUE TITLE
Feedback on madness-topic

### ISSUE THREAD

**Issue by Helena-LiT** [uzh/marugoto#110]
While I'm working on getting my topic-content to the test environment I would like to put some questions/concerns out here for discussion to give you @martindusinberre, @interrogator, @lfeine   an opportunity to give me some feedback:
1) As you know, I'm not quite happy with the original trigger video (a):

a) [Deinstitutionalized](https://www.youtube.com/watch?v=T3-1AYdfJ64) 

It mentions the main themes of my topic: institutionalization/state vs. community care/family, individual freedom vs. paternalism, care vs. neglect. However, I find it too sensationalist and I'm not sure Cor Media is a serius source.

There are a few other options: 
the first 3 or 4 minutes of:
b) [Deinstitutionalization - From Hospital to Community Care](https://www.youtube.com/watch?v=KLVhdrQwLjI)
This one seems more serious and even provides some metadata.

> This film was produced, edited and directed by Fernanda Berlinck and Taylor Duren for their final project Masters project at Goldsmiths, University of London.
A documentary exploring the topic of deinstitutionalization of mental health in the United Kingdom. Interviews include Sashi Sashidharan, Julian Leff and Graham Thornicroft, who all had important roles during the process.
Music: bensound.com
Fernanda Berlinck and Taylor Duren & Goldsmiths, University of London ©

However, it does not mention the negative side of deinstitutionalization as outspoken as the first.

Another option would be this:
c) [Right to Fail](https://www.pbs.org/wgbh/frontline/film/right-to-fail/)
This one has good credits and so on, but the problem with it is that I wouldn't even know where to cut it. The trailer is too short and the full film is too long.

2) I would like to collect some suggestions for the questionaire at the beginning.

My storyline blurres the boundaries of different realities (real world, game, novel) and identities (player's persona, in-game character, fictional character in a book). 
a) It seems fitting to have some interesting answers on the theme of "How strong is your sense of reality?"
b) Another one would be the issue of a player's autonomy over their own thoughts or their suggestibility.

**Comment by lfeine** [comment]
1. I think you've selected some interesting videos, but I agree about your concerns. I think of all of them, option b is probably the most professional one and fits the tone of previous LiT stories the most.
I also looked for some videos. I didn't really find anything about deinstitutionalization specifically, but here's a few interesting ones about mental health in general, maybe they'll point you in some direction or other:

Sybil: A Brilliant Hysteric by the NY Times https://www.youtube.com/watch?v=wRBZ0Kjisl4&t=527s This one is about multiple personality disorder and about how the media hype around it caused therapists to suggest false memories in many patients. 

Palestinians in Gaza face mounting mental health crisis | Al Jazeera English https://www.youtube.com/watch?v=wRBZ0Kjisl4&t=527s A more current news story that explores mental health during violent conflicts 

Mental healthcare goes mobile in Indonesia | Al Jazeera English https://www.youtube.com/watch?v=iDU8v_TrpQc A news story about an outreach program in Indonesia

Typhoon Haiyan leaves mentally ill caged and alone | The Guardian https://www.youtube.com/watch?v=xqL-HyVvQoY News story about mental illness in poor communities in the phillippines and how it leads to mistreatment and confinement of the mentally ill

2. Traditionally, games have dealt with this issue by making the game text itself unreliable. Maybe this video about a game dealing with psychosis will give you some ideas: https://www.youtube.com/watch?v=52flQkqj5gs (Senua's Sacrifice is considered one of the hallmarks of games dealing with mental illness). 
I think exploring this theme is very interesting, but try not to pose these questions directly. Instead of players getting directly questioned on their sense of reality, maybe ask if they've ever thought their friends might secretly hate them, people are laughing behind their back etc. Maybe if they've seen a ghost/believe in ghosts. Try also giving the player specific story situations in their options (so "yes I once saw my dead grandfather" instead of "yes I believe in ghosts"), and define distinct attitudes for the different answers.

**Comment by martindusinberre** [comment]
@lfeine thanks for all this feedback. I agree that it's better not to pose these questions directly. 
@Helena-LiT I see the problems--and even with the first video, I'm inclined to think that 5 minutes is about the maximum we should have for a trigger page. 
So a couple of ideas:
i) maybe don't worry about the trigger video and even the questions until you're almost at the end of the topic. Then it might be easier to formulate a set of questions rather than trying to second-guess yourself now. I certainly found it easier that way round for Defining Work.
ii) Having said that, if you're still thinking in the back of your mind about videos: what about something less explicitly "on topic", e.g. something about art and psychiatry or--given your interests and your training--something that points towards Heidelberg? E.g., I found the 2-minute video at the bottom of this SWR2 report interesting and I reckon it might capture the player's curiosity: https://www.swr.de/swr2/kunst-und-ausstellung/Kunst-So-gesehen-Kunstschaffende-mit-Psychatrieerfahrung-in-der-Sammlung-Prinzhorn,av-o1144016-100.html
We would need permission from SWR but there's time for that; and we would probably need to add English subtitles, too. But before we worry about that--what's your initial impressions?

**Comment by martindusinberre** [comment]
@Helena-LiT @lfeine Incidentally, I would also suggest we shift this discussion from github to gitlab (closed), as the topic is in development. @lfeine do you have access to this topic in gitlab?

**Comment by Helena-LiT** [comment]
Thanks, @lfeine and @martindusinberre for your comments and suggestions. I will move the issue to GitLab and continue our discussion there.

**Comment by Helena-LiT** [comment]
Since the transition to GitLab did not go as smoothly as I had imagined, I will write my short response here:
@lfeine Thanks for the video search and your thoughts about my initial selection. The video about the Philippines is closest to my topic but it also gives the impression that neglect in mental health provision is exclusively a problem of the Third World or poor countries in general.
@lfeine and @martindusinberre The many videos you suggested made me think about my topic and its focus. I am not doing a topic about madness in general, but specifically about the means and forms of managing madness. "Madness" is too large a topic designation and may confuse people by raising the wrong kind of expectations. I have decided to change the title to "Managing Lunatics." It resembles the "Defining Work" topic title, which obviously is also not simply about "Work" in general.
The comments about the questions are quite inspiring and I think this kind of strategy would be good within the game to reinforce the sense of loss of reality. It makes sense that these situational questions should not be asked directly, but I have the feeling that the discussion moved in a direction that is not related to my initial question. I don't think that the types of questions you suggested (and indirect questions in general) are suitable for the questionary at the beginning of the game. I don't have any specifc questions in mind for the questionary yet, but I am quite set about the general theme and it seems from your comments that this might be a good direction.

**Comment by martindusinberre** [comment]
@Helena-LiT Great, sounds good, and I like the new topic title. As I said, I think you can come back to the questions in a second iteration. I've just started doing this for Plantation Lives--and find that thinking of the questions now is helping me clarify what the whole topic is about. Have a look at the questions on the test environment if you want--they're a work in progress, but they help me as I now start revising that topic and adding the online storyline. Cheers, M
