### ISSUE TITLE
Game states not saved in autodeploy of test environment

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#112]
@interrogator @witlox This may only be relevant to the test environment. But just now, I signed out mid-game, then successfully pushed a change on github, then logged back in once the change had been made. But when I logged back in, my in-progress game was no longer visible in "Open Games". So it seems as if in-progress games are deleted when there is an autodeploy in the test environment.
This shouldn't delay us pushing an update to the production system today: if the problem is also in the production system, we'll only be able to see it only by pushing an update. And then we can try to fix it in the next 2-4 weeks before we do another update. But it's worth being aware of, and perhaps we can try to fix it in the test environment in the next couple of weeks.

**Comment by interrogator** [comment]
first, priority for this isn't really very high, it's not realted to live system, and is not a bug.

We have the option of saving/deleting the player states when we import, and we tend to delete them to avoid errors that come from breaking changes. the problem is, we can't easily know in autodeploy if the latest changes break the game structure, so i guess we delete to be on the safe side.

so, either we don't remove player states, which will cause errors that won't occur on live system, or we continue doing as we have been. my suggestion would be to leave things as is, but if you want we can change this and introduce some errors if you really prefer. @martindusinberre please decide :)

also sorry for not noticing these issues, as i said before, it's just because we were getting potentially  hundred emails from github every day...

**Comment by martindusinberre** [comment]
@interrogator No worries at all about not noticing these issues! I'm happy to follow your advice and leave things as they are. So I'll close this for the time being. Thanks, Martin
