### ISSUE TITLE
Use of backspace in Notebook

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#31]
Several players noted that when they are inputting in notebook, and then use the backspace button, they lose their entire notebook entry input; and in two cases, using the backspace button also sent them back to the very frontpage of the game. Can we fix this?

**Comment by christian-bernet** [comment]
I can't reproduce this with google Chrome. Do someone remember on wich browser it was?
Estimate: 2h

**Comment by martindusinberre** [comment]
Leyla will look at this and try to reproduce in the first instance. Please don't work on it until she reports back with a comment here.

**Comment by christian-bernet** [comment]
@lfeine can you please give us some feedback. Otherwise we can't fix it. thanks....

**Comment by lfeine** [comment]
I haven't been able to do a full test yet, however I think this issue might actually be related to #32 , since some browsers have backspace bound to the back button. This would cause issues quite similar to the oness experienced by the users here.
It will be fairly difficult to reproduce however, since backspace being bound to this functionality is both dependent on OS and browser (Firefox on Windows has it, Firefox on Linux does not, for instance).

**Comment by christian-bernet** [comment]
I think it is important to only reproduce the problem with
"Several players noted that when they are inputting in notebook, and then use the backspace button, they lose their entire notebook entry input;"

The other one is solved with: https://github.com/uzh/marugoto/issues/32
