### ISSUE TITLE
Remove notebookVisible on page

### ISSUE THREAD

**Issue by christian-bernet** [uzh/marugoto#39]
If we do not need that, then we should remove it in backend.
Because in frontend thats not working.
Estimate for removing in backend: 1 hour.

**Comment by martindusinberre** [comment]
I agree. Can we also update all of the json files once this has been done? (See new issue I've opened)

**Comment by christian-bernet** [comment]
ok. clean it up

**Comment by interrogator** [comment]
@martindusinberre let me know what should be removed/changed in JSON and I'll do it

**Comment by interrogator** [comment]
Unclear if this ever happened, but since unused I guess I can still remove from the JSON files...

**Comment by interrogator** [comment]
@martindusinberre this means, remove the entire true/false line for `notebookVisible` in page.json files? It does nothing?

**Comment by martindusinberre** [comment]
@interrogator yes, we've never used it, partly because the functionality of the notebook is now so much more sophisticated than we ever imagined. The only reason to have kept it would be to force the player to see something in the notebook, but I think we can do this with the content in a textComponent file now, so no worries. Plus, apparently the frontend isn't working anyway. So let's remove the entire line. 
Is it then possible to update the validator so that the line is deleted from all files we currently have, so that nobody building from previous content accidentally deploys it?

**Comment by interrogator** [comment]
I will remove it from the content, and then in the validator. I will just warn you that you need to pull once repos are updated :)
