### ISSUE TITLE
Multiple selections allowed on first page of trailer

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#84]
You are told you can only select one, but that's not true right now. Is there a fix by JSON possible? @martindusinberre

**Comment by martindusinberre** [comment]
@interrogator I think not: this is what Lena and I were trying last week, namely whether it was possible to put "maximum" and "1" as the value for a checkbox exercise instead of "minimum". But the answer is no... I may be able to rewrite the questions, or we may be able to turn them into radiobuttons and have 3 pages (1 question per page) rather than all the questions on a single page.

**Comment by martindusinberre** [comment]
OK, the way around it is multiple pageTransitions (as used a lot in day 4 of PlantationLives): click on one and you have a page transition. (The fact that the pages lead to the same is irrelevant: the player doesn't know that.)

**Comment by martindusinberre** [comment]
We've worked around this with multiple pageTransition.json files instead (which also replicates the choice mechanism the player will experience in chapter 4 of Plantation Lives). Please see the latest push I've just made.
