### ISSUE TITLE
Getting back to 'Welcome'/'Main' page once logged in?

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#88]
When not logged in, all is well. And now, when logged in, there is a nice 'Home' link in the bottom right, but when I click that, currently it takes me to `Your games`, when I expected it'd take me to the main page. This isn't terrible --- when you're logged into facebook for example, navigating 'home' or to `facebook.com` is to your wall, not to the facebook un-logged-in page.

But in our case, the un-logged-in page has important contextual information the user needs to be able to access while logged in. So, either the `home` button should take you back to the un-logged-in view, or there should be a big `Logout` button in `Your games`, clicking which takes you back to main. This needs a clear and immediate decision.

@martindusinberre , if `Your games` is going to be 'home' when logged in, I think it really needs to be more 'homey', right now it seems like a kind of administration page. More text, images, backgroundstyling, I don't know exactly what, but basically we need to pick a 'model' from some popular website and copy how it manages home when logged in and logged out (and how it allows you to log out!). I think the page should closely resemble the unlogged in home, same visual theme.

My two cents, I think it is a *big* mistake, that the user can't browse the welcome, citing (etc.) pages when they are logged in. More tabs may be added, with FAQ, guides, links, right now the user will need to keep logging in and out if they want to read about the game while playing it. 

Implicated problem: also, If I'm at https://marugoto.s3it.uzh.ch/storyline while logged in, I tried to get back to mainpage by changing the URL to https://marugoto.s3it.uzh.ch, but this redirects back to the original. What happens here depends on the above decision, I would expect doing this would at least take you to `Your games`?

So, is there actually no logout button anywhere? I see some basic code [here](https://github.com/uzh/marugoto-frontend/search?q=logout&unscoped_q=logout), but  @christian-bernet what is the status of 'logout' as a feature. Obviously logout must exist for every site where login does. Is it planned, overlooked, absent by design ... ?

Please tell me/edit/close if this is duplicate issue, or part of it is duplicate issue, I'm really surprised if it's been overlooked for this long. Also I believe this issue contains elements of both bug and feature, and furthermore, I think it's very very high prio. @witlox your thoughts welcome too, given the likelihood that we'll end up pair-programming the solution to this :P

**Comment by martindusinberre** [comment]
@interrogator Thanks for all these comments. I'll take them one by one:

- I'm happy that the newly developed "home" icon takes the player back to "Your Games". I've amended the texts both for "Your Games" and for "Topic Selection" to address exactly the problem you have identified in terms of relative lack of information on these pages, but the textual changes I asked for (see the Word file on #83 ) have still not been updated. So the first thing is to please follow **all** the changes I requested in #83 before that issue is closed. This is really the priority at this point.

- In terms of the look of the "Your Games" page: I don't mind it being so functional at the moment: I want the player to leave it as quickly as possible and get into the Topic Selection (which has nice graphics with the folder). So think that changing the look of the "Your Games" page is **not** a priority. (In an ideal world: yes, a bit more graphics, but really that's low on my list of priorities.) For what it's worth, the many people who have now tested this have never mentioned that they find "Your Games" problematic. All they need is more information--which is in the #83 edits.

- In terms of the URL: if you change it from .../storyline to .../games, you will return to "Your Games". But we don't want to encourage the player to do this: that's why we have the "home" icon. It's true that if we change it to /login then we *don't* return to the very front page.

- So: the only priority issue for us to discuss at this point, in my opinion, is the "Logout" functionality. I agree that it would be ideal to have the "Logout" option on the "Your Games" page. (**Only** on this page: we don't want the player to be able to logout from any other page of the game.) I note that there is already the "Sign Out" function in "Supervise Group Games", which you can get to also from the "Your Games" page. But in fact, this "Sign Out" function is effectively the same as the "home" icon, in that it takes you back to "Your Games". In an ideal world, then, it would be good to:

(i) change the code behind the "Sign Out" function in "Supervise Group Games" so that you really log out to the very front page of LiT
(ii) add a similar functionality to the "Your Games" page.
These are two separate feature issues which would need to be opened on github.

**But**: given that @interrogator and @witlox  would have to do this coding at this point, I do question whether it's a high priority or not. We still need to migrate the Trailer to the Production System; we still need to make sure that Shibboleth will be fully functional (even if, for the Trailer, Pim as deactivated it); and I would say we need to get the Trailer up and running before we do any more changes at this point--it's now been pretty rigorously tested and I wouldn't want to prioritise any other feature development **unless it can be done in just a few hours' work**, and then tested by us all before we go live with the trailer next week. 
If adding the "logout" functionality can't be done quickly, then I would say that getting the Trailer live is more important; and in the meantime, if @interrogator and @witlox  could then estimate how long such a feature change would take to code, then we could work out whether we could start work on it now or later in November/December.

More generally: this is one of several things that wasn't exactly overlooked, and certainly not by design. But I think none of us thought it through properly, especially as we were constantly firefighting other challenges in developing marugoto since last year. My instinct, although you know more about big IT projects, is that each project probably has such an "overlook" (or more than one) and this is ours. Many thanks indeed for pointing it out, and let me know what you think can be done.

**Comment by interrogator** [comment]
It turns out the 'sign out' inside supervisor mode was really just a button that sent you back to 'games'. So, it was like 'sign out' from supervisor mode, not from your account. We turned it into a 'Back to Games' button.

Then we implemented a logout button on game page (i.e. when logged in). It was done https://github.com/uzh/marugoto-frontend/commit/9d9717c9d8f0e6a1a59bc2e97897876d56170f4a and in the commits before. Is now on test system and works fine.

There shouldn't be any changes to URLs and stuff.

I still think it'd be nice to be able to view main page stuff while logged in, but the current fix is good enough for the time being, so we can close now!
