### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by interrogator** [uzh/marugoto#91]
> The game could use more information, about the project, contributing guidelines, and so on. There is now a basic About page (not yet deployed), awaiting the addition of more text content. In this issue @martindusinberre and I can figure out what content should be added. Below is some possible kinds of text to start us off. Note it's in markdown format, I'll convert the finished thing to HTML. Currently for example there is not much explanation of supervised games. Also there are no FAQs, etc., I think it's fine to use About as a bit of a catchall for now.

# About

> Stuff here

## Creating your own content

It's possible to create your own playable topics, simply by writing JSON files that Lives in Transit can import and serve.

Help pages for content development are on our roadmap. For now, however, please get in contact if you'd like to create your own content; we'd love to be able to add it to our site so that is playable by any user.

### Deploying your own Marugoto

Lives in Transit is 100 per cent open source and permissively licensed, which means that you can modify and run your own instance of the Marugoto engine, create and add your own topics, and so on. If you're interested in deploying an instance of the game yourself, please be in touch, as full deployment documentation is still in development.

**Comment by interrogator** [comment]
I will do `Contributor Guidelines`, basically inside a section talking to possible programmers who may want to help out.

**Comment by martindusinberre** [comment]
Great. Will have a proper look at this text tonight/tomorrow but we need to think about how we encourage potential topic creaters who have actual historical content etc. That's the challenge...

**Comment by martindusinberre** [comment]
I would have the order of the About page differently. First:

**The Software behind Lives in Transit** [or something more technical if you want]
Lives in Transit is powered by a custom-built software called Marugoto. ("Marugoto" means "the whole" in Japanese.) Marugoto is 100 per cent open source and permissively licensed, which means that you can modify and run your own instance of the Marugoto engine, create and add your own topics, and so on.

**Deploying your own Marugoto**

If you're interested in deploying an instance of the game yourself, please be in touch, as full deployment documentation is still in development.

**Creating your own Content**
We aim to expand Lives in Transit after its initial launch in spring 2020 by encouraging other universities and interested parties to develop their own, stand-alone topics to complement. We aim for content related to the practice of global history, broadly defined. It is possible to create this content simply by writing JSON files that Marugoto can import and serve to the frontend of Lives in Transit.

Help pages for content development are on our roadmap. For now, however, please get in contact if you'd like to create your own content; we'd love to help you on development so that your topic(s) can be played by any user. You can contact us by Twitter or (for longer enquiries) by emailing: globalhistory@hist.uzh.ch

**Comment by interrogator** [comment]
Thanks, this is a good start. Can we think of some other sections that will be included? From those I can create more content.

**Comment by martindusinberre** [comment]
OK, thanks, @interrogator . @lfeine @Helena-LiT  can you think of anything else you think should go on our new "about" tab? Please add draft text directly here.

**Comment by interrogator** [comment]
Is there some good text from various grant proposals etc, discussing aims and motivation of the project? That kind of stuff might be well re-used here. Influencers (i.e. Coltrane) etc can also go up. Basically I think, the more content, the better. The more info, the bigger and better the product appears (though I'm not a marketing guy of course)

**Comment by martindusinberre** [comment]
@interrogator Yes, there's a long proposal from earlier this year but actually Lena and I are in the process of putting in a smaller grant application now so I'll try to get this text to you asap. Can send you the longer proposal offline if you'd be interested? (It was for me to get the DSI fellowship)

**Comment by martindusinberre** [comment]
As discussed on rocketchat today, make #66 part of "About"

**Comment by interrogator** [comment]
> As discussed on rocketchat today, make #66 part of "About"

Will have this done today

**Comment by interrogator** [comment]
@martindusinberre any more text for about page right now? or should we close this for now?

**Comment by martindusinberre** [comment]
@interrogator  think we can close--thanks.
