### ISSUE TITLE
Choose a licence for playable demo

### ISSUE THREAD

**Issue by martindusinberre** [uzh/marugoto#96]
@lfeine This is the page Pim sent me for you to choose a licence from:
https://creativecommons.org/choose/
Danny wrote to me: "once we've done that then we can switch you over to updating the github repo for PL and demo, so let us know when ready"
@interrogator please let Leyla know if I've left out any information she needs on this.

**Comment by interrogator** [comment]
Nope, just pick as open as you can. From experience, you don't really have to worry that people are going to steal your work, the fact that it's yours is evident through git history anyway. We want open enough that people can go so far as to clone and modify a topic either to improve, remix, whatever. Might be nice if they still have to list the original authors, but even this doesn't really matter all that much, as there's very little chance of bad blood in this space!

**Comment by lfeine** [comment]
I think CC-BY-NC would fit our needs. This means:
- People can share the Demo (in altered or unaltered versions) in any license they like, including non-free ones. We could require share-alike here, meaning it must be shared under the same license. Let me know what you think. 
- Credit must be given 
- Only non-commercial use if shared (as I understand this is part of our requirements from our funding?)

The HTML code for including that license:
`<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.`

And here's the image they're using in case we also want to host it on our servers rather than pulling it from a third-party one:
![ccbync](https://user-images.githubusercontent.com/54706676/68310499-652e5200-00b0-11ea-81ea-e94abd3cd10c.png)

**Comment by martindusinberre** [comment]
Thanks, Leyla. @witlox @interrogator Will this do, then? If so, then please do whatever you need and update the project page.

**Comment by interrogator** [comment]
Yep, that seems appropriate to me. Added here: https://github.com/uzh/lit-demo/commit/2b42a5ce2b902732cb971a302f1ac108d69f67d9
